<a href="https://colab.research.google.com/github/PattuSri/workspace/blob/main/PattuSubhaLakshmi_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
fl=pd.read_csv("/content/drive/MyDrive/Assignment-1_Data.csv",delimiter=';')
fl

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,01.12.2010 08:26,"2,55",17850.0,United Kingdom
1,536365,WHITE METAL LANTERN,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
2,536365,CREAM CUPID HEARTS COAT HANGER,8,01.12.2010 08:26,"2,75",17850.0,United Kingdom
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,01.12.2010 08:26,"3,39",17850.0,United Kingdom
...,...,...,...,...,...,...,...
522059,581587,PACK OF 20 SPACEBOY NAPKINS,12,09.12.2011 12:50,"0,85",12680.0,France
522060,581587,CHILDREN'S APRON DOLLY GIRL,6,09.12.2011 12:50,"2,1",12680.0,France
522061,581587,CHILDRENS CUTLERY DOLLY GIRL,4,09.12.2011 12:50,"4,15",12680.0,France
522062,581587,CHILDRENS CUTLERY CIRCUS PARADE,4,09.12.2011 12:50,"4,15",12680.0,France
522063,581587,BAKING SET 9 PIECE RETROSPOT,3,09.12.2011 12:50,"4,95",12680.0,France

In [ ]:
#Items bought more
max= fl.groupby("Itemname")["Quantity"].transform("sum")
fl.loc[max.idxmax()]["Itemname"]

'PAPER CRAFT , LITTLE BIRDIE'

In [ ]:
#customer who buys more
fl.loc[fl.groupby("CustomerID")["Quantity"].transform("sum").idxmax()][["CustomerID"]]

CustomerID    14646.0
Name: 36881, dtype: object

In [ ]:
#customer who buys for more price
#fl['Price'] = fl['Price'].str.replace(',', '').astype(float)
fl.loc[fl.groupby("CustomerID")["Price"].transform("sum").idxmax()]["CustomerID"]
fl.groupby("CustomerID")["Price"].sum().sort_values(ascending=False)

AttributeError: ignored

In [ ]:
#customer bought recently
fl=fl.dropna(subset=["CustomerID"])
fl.sort_values(by=["Date"],ascending=False).head(50)

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
415017,573695,LANDMARK FRAME NOTTING HILL,2,31.10.2011 17:13,125.0,15023.0,United Kingdom
415021,573695,SET OF 2 TRAYS HOME SWEET HOME,2,31.10.2011 17:13,995.0,15023.0,United Kingdom
415014,573695,LANDMARK FRAME CAMDEN TOWN,2,31.10.2011 17:13,125.0,15023.0,United Kingdom
415015,573695,LANDMARK FRAME OXFORD STREET,1,31.10.2011 17:13,125.0,15023.0,United Kingdom
415016,573695,LANDMARK FRAME LONDON BRIDGE,2,31.10.2011 17:13,125.0,15023.0,United Kingdom
415018,573695,LANDMARK FRAME COVENT GARDEN,2,31.10.2011 17:13,125.0,15023.0,United Kingdom
415019,573695,LANDMARK FRAME BAKER STREET,2,31.10.2011 17:13,125.0,15023.0,United Kingdom
415020,573695,WHITE HANGING HEART T-LIGHT HOLDER,32,31.10.2011 17:13,255.0,15023.0,United Kingdom
415022,573695,WALL ART KEEP CALM,1,31.10.2011 17:13,825.0,15023.0,United Kingdom
415023,573695,FOOT STOOL HOME SWEET HOME,4,31.10.2011 17:13,995.0,15023.0,United Kingdom
415013,573695,RABBIT NIGHT LIGHT,9,31.10.2011 17:13,208.0,15023.0,United Kingdom
414981,573665,PHOTO FRAME CORNICE,4,31.10.2011 16:24,295.0,13982.0,United Kingdom
414983,573666,GIANT 50'S CHRISTMAS CRACKER,4,31.10.2011 16:24,289.0,15977.0,United Kingdom
414984,573666,CHRISTMAS HANGING TREE WITH BELL,48,31.10.2011 16:24,39.0,15977.0,United Kingdom
414985,573666,CHRISTMAS HANGING STAR WITH BELL,48,31.10.2011 16:24,39.0,15977.0,United Kingdom
414982,573666,WHITE CHRISTMAS STAR DECORATION,25,31.10.2011 16:24,42.0,15977.0,United Kingdom
414986,573666,HANGING HEART WITH BELL,48,31.10.2011 16:24,39.0,15977.0,United Kingdom
414987,573666,SWISS CHALET TREE DECORATION,24,31.10.2011 16:24,29.0,15977.0,United Kingdom
414988,573666,OFFICE MUG WARMER POLKADOT,2,31.10.2011 16:24,295.0,15977.0,United Kingdom
414979,573665,RED WOOLLY HOTTIE WHITE HEART.,4,31.10.2011 16:24,425.0,13982.0,United Kingdom
414980,573665,WORLD WAR 2 GLIDERS ASSTD DESIGNS,48,31.10.2011 16:24,29.0,13982.0,United Kingdom
414990,573666,SET 36 COLOUR PENCILS DOLLY GIRL,2,31.10.2011 16:24,125.0,15977.0,United Kingdom
415009,573666,4 PEAR BOTANICAL DINNER CANDLES,36,31.10.2011 16:24,125.0,15977.0,United Kingdom
414978,573665,HOT WATER BOTTLE TEA AND SYMPATHY,4,31.10.2011 16:24,425.0,13982.0,United Kingdom
414977,573665,RED RETROSPOT CHARLOTTE BAG,10,31.10.2011 16:24,85.0,13982.0,United Kingdom
414976,573665,GARDENERS KNEELING PAD KEEP CALM,1,31.10.2011 16:24,165.0,13982.0,United Kingdom
414975,573665,SCOTTIE DOG HOT WATER BOTTLE,4,31.10.2011 16:24,495.0,13982.0,United Kingdom
414974,573665,BINGO SET,4,31.10.2011 16:24,375.0,13982.0,United Kingdom
414989,573666,OFFICE MUG WARMER BLACK+SILVER,2,31.10.2011 16:24,295.0,15977.0,United Kingdom
414996,573666,RED WOOLLY HOTTIE WHITE HEART.,2,31.10.2011 16:24,425.0,15977.0,United Kingdom
414991,573666,COLOURING PENCILS BROWN TUBE,2,31.10.2011 16:24,125.0,15977.0,United Kingdom
415000,573666,RED KITCHEN SCALES,2,31.10.2011 16:24,85.0,15977.0,United Kingdom
415006,573666,WICKER WREATH SMALL,6,31.10.2011 16:24,145.0,15977.0,United Kingdom
415005,573666,WHITE WICKER STAR,6,31.10.2011 16:24,21.0,15977.0,United Kingdom
415004,573666,4 VANILLA BOTANICAL CANDLES,24,31.10.2011 16:24,125.0,15977.0,United Kingdom
415003,573666,HEART OF WICKER SMALL,3,31.10.2011 16:24,165.0,15977.0,United Kingdom
415002,573666,SMALL WHITE HEART OF WICKER,6,31.10.2011 16:24,165.0,15977.0,United Kingdom
415001,573666,MINT KITCHEN SCALES,2,31.10.2011 16:24,85.0,15977.0,United Kingdom
414999,573666,IVORY KITCHEN SCALES,2,31.10.2011 16:24,85.0,15977.0,United Kingdom
414992,573666,SET 36 COLOUR PENCILS LOVE LONDON,2,31.10.2011 16:24,125.0,15977.0,United Kingdom
414998,573666,REX CASH+CARRY JUMBO SHOPPER,2,31.10.2011 16:24,95.0,15977.0,United Kingdom
414997,573666,HOT WATER BOTTLE TEA AND SYMPATHY,2,31.10.2011 16:24,425.0,15977.0,United Kingdom
414972,573665,RECIPE BOX RETROSPOT,3,31.10.2011 16:24,295.0,13982.0,United Kingdom
414995,573666,KNITTED UNION FLAG HOT WATER BOTTLE,2,31.10.2011 16:24,425.0,15977.0,United Kingdom
414994,573666,ENGLISH ROSE HOT WATER BOTTLE,2,31.10.2011 16:24,425.0,15977.0,United Kingdom
414993,573666,BREAD BIN DINER STYLE IVORY,1,31.10.2011 16:24,1695.0,15977.0,United Kingdom
414973,573665,SET/10 RED POLKADOT PARTY CANDLES,8,31.10.2011 16:24,125.0,13982.0,United Kingdom
414966,573665,VINTAGE SNAP CARDS,8,31.10.2011 16:24,85.0,13982.0,United Kingdom
414971,573665,VINTAGE HEADS AND TAILS CARD GAME,8,31.10.2011 16:24,125.0,13982.0,United Kingdom
414956,573665,SOLDIERS EGG CUP,12,31.10.2011 16:24,125.0,13982.0,United Kingdom

In [ ]:
#customer buys frequently
fl.groupby("CustomerID")["BillNo"].nunique().sort_values(ascending=False)

CustomerID
12748.0    210
17841.0    124
13089.0     97
14606.0     93
15311.0     91
          ...
13774.0      1
16248.0      1
16247.0      1
13778.0      1
12346.0      1
Name: BillNo, Length: 4297, dtype: int64

**bold text**# New Section

*italicized text*# New Section